name: CI – Challenge Accessibility Tracker

on:
  pull_request_target:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: write
jobs:
  run-challenge:
    uses: doublebitsrl/ci-common/.github/workflows/test-challenge.yml@main
    with:
      challengeId: accessibility-tracker
    secrets:
      PRIVATE_REPO_PAT: ${{ secrets.PRIVATE_REPO_PAT }}
